### ISSUE TITLE
Unhanded exception on install

### ISSUE THREAD

**Issue by null-von-sushi** [HarshalKudale/NoMoreEdge#10]
An exception occurred during a WebClient request

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Program Files (Arm)\Microsoft\Edge\Application\NoMoreEdge.exe'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at NoMoreEdgeSetup.NoMoreEdgeSetupForm.installApp(String path, String edgepath, String newedge, String destFile, String engine)
   at NoMoreEdgeSetup.Form1.btn_install_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
NoMoreEdgeSetup
    Assembly Version: 1.5.0.3
    Win32 Version: 1.5.0.3
    CodeBase: file:///C:/Users/System%20Operator/Downloads/NoMoreEdgeSetup.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4395.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4455.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by HarshalKudale** [comment]
It looks you do not have edge installed. This software will copy the NoMoreEdge.exe to msedge.exe and you already uninstalled edge so this is happening.

**Comment by null-von-sushi** [comment]
But... I do have edge installed?
Is there anything I can do to figure out why this error occurs? Because Edge is installed (tbh I didn't even know Windows lets you uninstall it)

**Comment by HarshalKudale** [comment]
Then you must have arm system. Can you please find the nsedge.exe location and post it here so I can add arm support. Can you confirm if your device is arm and if it is are you willing to provide arm  specific windows file paths for edge so to add support for arm systems

**Comment by null-von-sushi** [comment]
Oh yeah, I have a surface pro X. 
Did you mean `msedge.exe`?
If so, that one is in
`"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"`

I guess edge is not ported to ARM yet? At least there is no edge folder anywhere in `C:\Program Files (Arm)`

What other fielpaths would you like me to check?

**Comment by HarshalKudale** [comment]
I was using program files global variable. so that was defaulting to x86 or arm path according to architecture. I guess I will just provide absolute path to x86 for all architecture in next update.
for workaround you can install NoMoreEdge from setup and then put the NoMoreEdge exe from same release in msedge.exe folder and ceate a copy of msedge.exe in same location as msedge_backup.exe check if it works.

**Comment by null-von-sushi** [comment]
I made a symbolic link from the X86 folder to the ARM folder (`mklink /d "C:\Program Files (Arm)\Microsoft" "C:\Program Files (x86)\Microsoft"`). This seems to have let to me run the setup file normally as a workaround. Thank you.

Thank you
